---
name: Build & Publish to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:

      - name: GitHub Checkout
        uses: actions/checkout@v3
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allow_empty_commit: true
          publish_dir: ./public
          cname: pasapalabra.ernesto.es
          enable_jekyll: false
